### ISSUE TITLE
Documentation when?

### ISSUE THREAD

**Issue by Fern-Leaves** [Sxip/critters#2]
when on earth will there be a tutorial on how to get a CrittersBox server up and running?!?!?!??!?!?!?!?!??!?!?!?!?!?!?!?!?!??!?!?!

**Comment by missaustraliana** [comment]
I REALLY DON'T KNOW!!!!

I CANT SET IT UP EITHER!!

**Comment by Sxip** [comment]
Hello, I will write documentation soon. 

Sorry for not responding sooner, I have been busy.

**Comment by missaustraliana** [comment]
@Sxip many people are confused on how to use it...

There was no instructions with the bundle.

Maybe add a instructions.txt?? or a yt link..

Thanks,
TechnoByte (BoxCritters)
